# Generated by Django 4.2.9 on 2024-01-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cad_livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('R', 'Romance'), ('T', 'Terror')], max_length=1)),
            ],
        ),
    ]
