# Generated by Django 4.2.9 on 2024-01-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data_nacimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
